name: fastcrud-api
replicaCount: 1

image:
  repository: tamas99/fastcrud-api
  tag: "0.1"
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  type: ClusterIP
  port: 80

env:
  - name: DATABASE_URL
    value: sqlite+aiosqlite:///./test.db
